name=Mintrix
version=1.0.6
author=Janik Heiler
maintainer=Janik Heiler
sentence=Library for the Mintrix project at the KKG.
paragraph=This library enables students to easily code programs for the Mintrix project.
category=Device Control
url=https://github.com/whoelsethanjesus/Mintrix
architectures=esp8266
depends=FastLED, Arduino_JSON
